TrajectoryPlannerROS:
  max_vel_x: 0.1
  min_vel_x: 0.01
  max_vel_theta: 0.075
  min_vel_theta: 0.01
  min_in_place_vel_theta: 0.01

  #max_rotational_vel: 0.05
  #min_in_place_rotational_vel: 0.0

  acc_lim_theta: 1.6
  acc_lim_x: 0.75
  acc_lim_y: 0.75

  holonomic_robot: false
  oscillation_reset_dist: 0.1
