TrajectoryPlannerROS:
  max_vel_x: 0.181
  min_vel_x: 0.05
  max_rotational_vel: 0.125
  min_in_place_rotational_vel: 0.05

  acc_lim_th: 2.6
  acc_lim_x: 1.75
  acc_lim_y: 1.75

  holonomic_robot: false
