obstacle_range: 2.5
raytrace_range: 3.5
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
#robot_radius: ir_of_robot
inflation_radius: 0.2

observation_sources: assembled_cloud

#laser_scan_sensor: {sensor_frame: frame_name, data_type: LaserScan, topic: topic_name, #marking: true, clearing: true}
#add frame, topic for lidar scan

assembled_cloud: {sensor_frame: map, data_type: PointCloud, topic: assembled_cloud, marking: true, clearing: true}
#add frame, topic for point cloud scan from tilting lidar
