obstacle_range: 2.5
raytrace_range: 3.5
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
#robot_radius: ir_of_robot
inflation_radius: 0.2

observation_sources: point_cloud_octomap #scanMap

#scanMap: {sensor_frame: laser, data_type: LaserScan, topic: scanMap, marking: true, clearing: true}
#add frame, topic for lidar scan

point_cloud_octomap : {sensor_frame: laser, data_type: PointCloud, topic: point_cloud_octomap, marking: true, clearing: true}
#add frame, topic for point cloud scan from tilting lidar
