<?xml version="1.0"?>
<robot name="aar2" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="PI" value="3.1415926535897931" />

  <xacro:property name="wheelbase" value="1.1" />
  <xacro:property name="track" value="0.82" /> 
  <xacro:property name="wheel_vertical_offset" value="-0.35" />
  <xacro:property name="footprint_vertical_offset" value="0" />

  <xacro:property name="wheel_radius" value="0.17" /> 
  <xacro:property name="wheel_width" value="0.13" /> 

  <xacro:property name="chassis_length" value="1.1" />
  <xacro:property name="chassis_width" value="0.82" /> 
  <xacro:property name="chassis_height" value="0.17" /> 

  <xacro:property name="dummy_inertia" value="1e-09"/>

  <xacro:property name="mount_spacing" value="0.120" />

  <material name="dark_grey"><color rgba="0.2 0.2 0.2 1.0" /></material>
  <material name="light_grey"><color rgba="0.4 0.4 0.4 1.0" /></material>
  <material name="yellow"><color rgba="0.8 0.8 0.0 1.0" /></material>
  <material name="black"><color rgba="0.15 0.15 0.15 1.0" /></material>

  <xacro:macro name="wheel" params="prefix *joint_pose">

    <link name="${prefix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
		<cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="-0.0001 0 -0.00001" rpy="0 0 0"/>
        <mass value="0.477"/>
        <inertia
          ixx="0.0024" ixy="0" ixz="0"
          iyy="0.0013" iyz="0"
          izz="0.0013"/>
      </inertial>
    </link>

    <gazebo reference="${prefix}_wheel_link">
      <material>Gazebo/DarkGrey</material>
    </gazebo>

    <joint name="${prefix}_wheel" type="fixed">
      <parent link="chassis_link"/>
      <child link="${prefix}_wheel_link" />
      <xacro:insert_block name="joint_pose" />
      <axis xyz="0 1 0" />
    </joint>

  </xacro:macro>

  <xacro:wheel prefix="front_left">
    <origin xyz="${wheelbase/1.1*0.55} ${track/0.82*0.41} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="front_right">
    <origin xyz="${wheelbase/1.1*0.55} ${-track/0.82*0.41} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
<xacro:wheel prefix="mid_left">
    <origin xyz="${-wheelbase/1.1*0.11} ${track/0.82*0.41} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="mid_right">
    <origin xyz="${-wheelbase/1.1*0.11} ${-track/0.82*0.41} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="rear_left">
    <origin xyz="${-wheelbase/1.1*0.55} ${track/0.82*0.41} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="rear_right">
    <origin xyz="${-wheelbase/1.1*0.55} ${-track/0.82*0.41} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>

  <link name="base_link"></link>

  <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="chassis_link" />
  </joint>

  <link name="chassis_link">
    <visual>
      <origin xyz="0 0 ${footprint_vertical_offset}" rpy="0 0 0"/>
      <geometry>
        <box size ="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="dark_grey" />
    </visual>
    <collision>
      <origin xyz="0 0 ${chassis_height/2}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <inertial>
      <!-- Center of mass -->
      <origin xyz="0.012  0.002 0.067" rpy="0 0 0"/>
      <mass value="16.523"/> 
      <!-- Moments of inertia: ( chassis without wheels ) -->
      <inertia
        ixx="0.3136" ixy="-0.0008" ixz="0.0164"
        iyy="0.3922" iyz="-0.0009"
        izz="0.4485"/>
      </inertial>
  </link>

  <!--link name="fenders_link">
    <visual>
      <origin xyz="0 0 ${footprint_vertical_offset}" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <mesh filename="package://aar2_description/meshes/aar2-fenders.stl"/>
      </geometry>
      <material name="yellow" />
    </visual>
  </link>
  <joint name="fenders_joint" type="fixed">
    <parent link="chassis_link" />
    <child link="fenders_link" />
  </joint>

  < TODO: Make this internal_imu_link or something, and use a mixed-in xacro
       to supply the joint between it and imu_link. This is important so that imu_link
       always points to the "active" IMU. When an upgrade IMU is connected, the
       internal_imu_link should remain, but imu_link should point to the upgrade one. -->
  <link name="imu_link">
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="${dummy_inertia}" ixy="0.0" ixz="0.0" iyy="${dummy_inertia}" iyz="0.0" izz="${dummy_inertia}"/>
    </inertial>
  </link>
  <joint name="imu_joint" type="fixed">
    <parent link="chassis_link" />
    <child link="imu_link" />
	<origin xyz="0 0 0" rpy="1.57 0 0" />
  </joint>

  <!-- TODO: Same note as applies to imu_link -->
  <link name="navsat_link">
    <visual>
      <geometry>
        <cylinder radius="0.026" length="0.016" />
      </geometry>
      <origin xyz="0 0 0.008" />
      <material name="black" />
    </visual>
  </link>
  <joint name="navsat_joint" type="fixed">
    <parent link="chassis_link" />
    <child link="navsat_link" />
    <origin xyz="-0.180 0.126 0.1815" />
  </joint>

  <link name="mid_mount"></link>
  <joint name="mid_mount_joint" type="fixed">
    <parent link="chassis_link" />
    <child link="mid_mount" />
    <origin xyz="0 0 ${chassis_height}" />
  </joint>

  <link name="rear_mount"></link>
  <joint name="rear_mount_joint" type="fixed">
    <parent link="mid_mount" />
    <child link="rear_mount" />
    <origin xyz="${-mount_spacing} 0 0" />
  </joint>
  
  <link name="front_mount"></link>
  <joint name="front_mount_joint" type="fixed">
    <parent link="mid_mount" />
    <child link="front_mount" />
    <origin xyz="${mount_spacing} 0 0" />
  </joint>

  <!-- Optional standard accessories, including their simulation data. The rendering
       of these into the final description is controlled by optenv variables, which
       default each one to off.-->
<xacro:include filename="accessories/sick_lms1xx.urdf.xacro" />
    <sick_lms1xx_mount prefix="$(optenv AAR2_LASER_MOUNT front)"
                       topic="$(optenv AAR2_LASER_TOPIC scan)" />

    <joint name="$front_laser_mount_joint" type="fixed">
      <origin xyz="$(optenv AAR2_LASER_OFFSET 0 0 0)"
              rpy="$(optenv AAR2_LASER_RPY 0 0 0)" />
      <parent link="$(optenv AAR2_LASER_MOUNT front)_mount" />
      <child link="$(optenv AAR2_LASER_MOUNT front)_laser_mount" />
    </joint>

</robot>
